version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: test_task
    command: ["/test_task/docker/app.sh"]
    ports:
      - 7788:8000
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
